# 仅提供MC机器人的相关功能 如果你还想让机器人实现更多功能 请自行开发
# 开源地址: https://gitee.com/msg_dw/mc-qqbot

# 全局配置
global:
  # 日志类型 [CONSOLE, FILE, NONE]
  # CONSOLE 控制台日志
  # FILE 文件日志 (保存30天)
  # NONE 不记录日志
  logger-type: CONSOLE
  # 登录类型 [ANDROID_PAD, ANDROID_PHONE, ANDROID_WATCH]
  # ANDROID_PAD 安卓平板
  # ANDROID_PHONE 安卓手机
  # ANDROID_WATCH 安卓手表
  login-type: ANDROID_WATCH

# 机器人配置
bot:
  # QQ号
  qq-code:
  # 密码
  qq-password: