main: ${project.group}.boot.PluginBoot

name: ${project.name}
version: ${project.version}
author: msg_dw

api-version: 1.13

lib-download: true
lib-version: ${taboolib.tabooLibVersion}
loader-version: ${taboolib.loaderVersion}
